export const LOGIN_FAILED_ROOM_FULL = 'LOGIN_FAILED_ROOM_FULL';
export const LOGIN_FAILED_CANNOT_CONNECT = 'LOGIN_FAILED_CANNOT_CONNECT';
export const LOGIN_LOADING = 'LOGIN_PROCESSING';
export const LOGIN_OK = 'LOGIN_OK';
export const LOGIN_UNSET = 'LOGIN_UNSET';
